### ISSUE TITLE
Second Dice action has a blue background and is not working

### ISSUE THREAD

**Issue by Timac** [viddie/sdDice#1]
Steps to reproduce:

1. Drag and drop a Dice action to the grid view in the Stream Deck app. Note that the action is working properly.
2. Drag and drop another Dice action to the grid view in the Stream Deck app

Result: This second action has a blue background and is not working.

<img width="952" alt="screenshot" src="https://user-images.githubusercontent.com/738543/79995157-2736b600-84b7-11ea-91ed-d2f26e849a5f.png">

**Comment by viddie** [comment]
Should be resolved, I'll notify the Stream Deck team to push the new version later today
